### ISSUE TITLE
License incompatible with Apache 2.0

### ISSUE THREAD

**Issue by judahrand** [uccidibuti/bitrush-index#1]
I'm interested in trying to use this crate to implement bitmap indexes in [lance](https://github.com/lancedb/lance). However, `lance` is an Apache 2.0 licensed project and this crate is GPL v3. Unfortunately, [GPL v3 software cannot be included in Apache 2.0 software](https://www.apache.org/licenses/GPL-compatibility.html) (though the other direction is fine).

Would it be possible to change the license on this crate to something more permissive? It would be great if this project could be used in the wider Rust + Apache Arrow ecosystem!

**Comment by uccidibuti** [comment]
It seem a cool project lance, I'll try it. Is it good if I change the license to LGPL?  I would appreciate it if you mention the bitmap compression method that I developed with the aim of building the best bitmap index  on high-cardinality columns (i16, i32, i64),  in your project [OZBCBitmap](https://github.com/uccidibuti/bitrush-index/blob/master/src/ozbcbitmap/mod.rs).

**Comment by uccidibuti** [comment]
@judahrand I close the ticket. If you still want a more permissive license let me know.
